server:
  port: 7001
spring:
  application:
    name: customer
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: admin
    password: admin1234
    url: jdbc:oracle:thin:/@database-1.cx1w7aebhl7k.us-west-2.rds.amazonaws.com:1521/ORCL
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    enabled: true